# Generated by Django 5.1.2 on 2024-11-04 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0002_signature"),
        ("duty", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffroles",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_roles",
                to="corecode.subject",
            ),
        ),
    ]
