# Generated by Django 5.1.2 on 2024-11-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0003_dailyschedule_classschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classschedule",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional description for event activities",
                max_length=200,
            ),
        ),
    ]
