# Generated by Django 5.1.2 on 2024-11-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0004_alter_classschedule_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classschedule",
            name="end_time",
            field=models.TimeField(default="00:00"),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="start_time",
            field=models.TimeField(default="00:00"),
        ),
        migrations.AlterField(
            model_name="dailyschedule",
            name="end_time",
            field=models.TimeField(
                default="00:00", help_text="End time for school activities."
            ),
        ),
        migrations.AlterField(
            model_name="dailyschedule",
            name="start_time",
            field=models.TimeField(
                default="00:00", help_text="Start time for school activities."
            ),
        ),
    ]
