# Generated by Django 5.1.2 on 2024-11-05 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0005_alter_classschedule_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classschedule",
            name="end_time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="start_time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name="dailyschedule",
            name="end_time",
            field=models.TimeField(
                default=datetime.time(0, 0), help_text="End time for school activities."
            ),
        ),
        migrations.AlterField(
            model_name="dailyschedule",
            name="start_time",
            field=models.TimeField(
                default=datetime.time(0, 0),
                help_text="Start time for school activities.",
            ),
        ),
    ]
