# Generated by Django 5.0.4 on 2024-08-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoollocation',
            name='district',
        ),
        migrations.RemoveField(
            model_name='schoollocation',
            name='region',
        ),
        migrations.RemoveField(
            model_name='schoollocation',
            name='street',
        ),
        migrations.RemoveField(
            model_name='schoollocation',
            name='ward',
        ),
        migrations.AddField(
            model_name='schoollocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='schoollocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='schoollocation',
            name='end_time',
            field=models.TimeField(default='19:00'),
        ),
        migrations.AlterField(
            model_name='schoollocation',
            name='start_time',
            field=models.TimeField(default='07:00'),
        ),
    ]
