# Generated by Django 5.0.4 on 2024-08-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_schoollocation_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=35, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='schoollocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=35, max_digits=40, null=True),
        ),
    ]
