# Generated by Django 5.0.4 on 2024-08-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_alter_schoollocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollocation',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
