# Generated by Django 5.0.4 on 2024-08-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_schoollocation_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollocation',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
    ]
