# Generated by Django 5.0.4 on 2024-08-15 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_customuser_profile_picture'),
        ('parents', '0012_remove_invoicecomments_term'),
        ('students', '0009_student_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretaryAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default=None)),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('date_updated_comments', models.DateTimeField(auto_now=True)),
                ('mark_student_comment', models.BooleanField(default=False)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parents.studentcomments')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parentuser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
