# Generated by Django 5.0.4 on 2024-08-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0003_alter_secretaryanswers_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaryanswers',
            name='answer',
            field=models.TextField(),
        ),
    ]
