# Generated by Django 5.0.4 on 2024-08-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0005_secretaryanswers_mark_secretary_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretaryanswers',
            old_name='mark_secretary_comment',
            new_name='mark_secretary_answer',
        ),
    ]
