# Generated by Django 5.0.4 on 2024-07-02 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="group",
        ),
        migrations.AlterField(
            model_name="staff",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in the right format!",
                        regex="^\\+255[0-9]{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="occupation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
