# Generated by Django 5.0.4 on 2024-08-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_alter_staff_passport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='passport_photo',
            field=models.ImageField(blank=True, upload_to='staffs/passports/'),
        ),
    ]
