# Generated by Django 4.2.17 on 2024-12-11 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_staffattendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in the right format! Use +255XXXXXXXXX", regex='^\\+255[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='occupation',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('administrator', 'Administrator'), ('support_staff', 'Support Staff')], max_length=50, null=True),
        ),
    ]
