# Generated by Django 5.0.4 on 2024-07-03 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("students", "0007_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="students.student",
            ),
        ),
    ]
