# Generated by Django 5.0.4 on 2024-07-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_invoice_student_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="student_name",
        ),
    ]
