# Generated by Django 5.0.4 on 2024-07-03 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0001_initial"),
        ("finance", "0004_remove_invoice_student_name"),
        ("students", "0008_delete_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="class_for",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="corecode.studentclass",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="corecode.academicsession",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
            ),
        ),
    ]
