# Generated by Django 5.0.4 on 2024-07-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_invoice_class_for_alter_invoice_session_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'get_latest_by': 'date_paid'},
        ),
    ]
