# Generated by Django 5.0.4 on 2024-07-26 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
        ('finance', '0006_alter_receipt_options'),
        ('students', '0009_student_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUniform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.studentclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniform_type', models.CharField(choices=[('SHATI', 'Shati'), ('SKETI/KAPTULA', 'Sketi/Kaptula'), ('SWETA', 'Sweta'), ('SOKSI', 'Soksi'), ('T-SHIRT', 'T-Shirt'), ('KAPTULA YA MICHEZO', 'Kaptula ya Michezo')], max_length=20)),
                ('quantity', models.CharField(choices=[('Jozi 1', 'Jozi 1'), ('Jozi 2', 'Jozi 2')], default='Jozi 2', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.studentclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicterm')),
            ],
        ),
    ]
