# Generated by Django 5.0.4 on 2024-08-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_salaryinvoice_allowance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='uniform',
            name='uniform_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.uniformtype'),
        ),
    ]
