# Generated by Django 4.2.16 on 2024-11-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0002_signature'),
        ('finance', '0012_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryinvoice',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.academicsession'),
        ),
    ]
