# Generated by Django 5.0.4 on 2024-08-04 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0002_remove_staff_group_alter_staff_mobile_number_and_more'),
        ('students', '0009_student_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('issue_file', models.FileField(blank=True, null=True, upload_to='discipline_issues/')),
                ('reported_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to='staffs.staff')),
                ('reported_by_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to='students.student')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField()),
                ('date_taken', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='disprine.disciplineissue')),
            ],
        ),
    ]
