# Generated by Django 5.0.4 on 2024-08-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disprine', '0001_initial'),
        ('staffs', '0002_remove_staff_group_alter_staff_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='discipline_issue',
        ),
        migrations.AddField(
            model_name='action',
            name='action_taker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
            preserve_default=False,
        ),
    ]
