# Generated by Django 5.0.4 on 2024-08-04 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disprine', '0002_remove_action_discipline_issue_action_action_taker'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='discipline_issue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='disprine.disciplineissue'),
            preserve_default=False,
        ),
    ]
