# Generated by Django 5.0.4 on 2024-07-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_remove_student_parent_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="archive_date",
        ),
        migrations.RemoveField(
            model_name="student",
            name="archived",
        ),
    ]
