# Generated by Django 5.0.4 on 2024-07-02 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_remove_student_archive_date_remove_student_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="parent_mobile_number",
        ),
        migrations.AddField(
            model_name="student",
            name="father_mobile_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^\\+255[0-9]{9}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_mobile_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^\\+255[0-9]{9}$",
                    )
                ],
            ),
        ),
    ]
