# Generated by Django 5.0.4 on 2024-07-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_remove_student_parent_mobile_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="parent_student_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
