# Generated by Django 5.0.4 on 2024-07-03 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_student_parent_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="father_mobile_number",
            field=models.CharField(
                blank=True,
                default="+255",
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^\\+255[0-9]{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_mobile_number",
            field=models.CharField(
                blank=True,
                default="+255",
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^\\+255[0-9]{9}$",
                    )
                ],
            ),
        ),
    ]
