# Generated by Django 5.0.4 on 2024-07-03 13:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0001_initial"),
        ("students", "0006_alter_student_father_mobile_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("registration_number", models.CharField(max_length=200)),
                ("firstname", models.CharField(max_length=200)),
                ("middle_name", models.CharField(blank=True, max_length=200)),
                ("surname", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(default=django.utils.timezone.now)),
                (
                    "date_of_admission",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "father_mobile_number",
                    models.CharField(
                        blank=True,
                        default="+255",
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entered mobile number isn't in a right format!",
                                regex="^\\+255[0-9]{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "mother_mobile_number",
                    models.CharField(
                        blank=True,
                        default="+255",
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entered mobile number isn't in a right format!",
                                regex="^\\+255[0-9]{9}$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("others", models.TextField(blank=True)),
                (
                    "passport",
                    models.ImageField(blank=True, upload_to="students/passports/"),
                ),
                ("parent_student_id", models.IntegerField(blank=True, null=True)),
                (
                    "current_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="corecode.studentclass",
                    ),
                ),
            ],
            options={
                "ordering": ["firstname", "middle_name", "surname"],
            },
        ),
    ]
