# Generated by Django 5.0.4 on 2024-07-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_archive"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Archive",
        ),
    ]
