# Generated by Django 5.0.4 on 2024-07-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_delete_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
