# Generated by Django 5.0.4 on 2024-06-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentuser",
            name="parent_first_name",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name="parentuser",
            name="parent_last_name",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
