# Generated by Django 5.0.4 on 2024-06-18 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_parentuser_parent_first_name_and_more"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentuser",
            name="parent_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="parentuser",
            name="parent_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="parentuser",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
            ),
        ),
    ]
