# Generated by Django 5.0.4 on 2024-06-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_remove_parentuser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Spanish"), ("fr", "French")],
                default="en",
                max_length=10,
            ),
        ),
    ]
