# Generated by Django 5.0.4 on 2024-06-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentcomments",
            name="comment",
            field=models.TextField(default=None),
        ),
    ]
