# Generated by Django 5.0.4 on 2024-06-23 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0004_invoicecomments"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicecomments",
            name="date_commented",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoicecomments",
            name="date_updated_comments",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="parentcomments",
            name="date_commented",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parentcomments",
            name="date_updated_comments",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="studentcomments",
            name="date_commented",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentcomments",
            name="date_updated_comments",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
