# Generated by Django 5.0.4 on 2024-06-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0001_initial"),
        ("parents", "0006_invoicecomments_satisfied"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentcomments",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="corecode.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="parentcomments",
            name="term",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="corecode.academicterm",
            ),
        ),
    ]
