# Generated by Django 5.0.4 on 2024-06-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0007_parentcomments_session_parentcomments_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentcomments",
            name="mark_comment",
            field=models.BooleanField(default=False),
        ),
    ]
