# Generated by Django 5.0.4 on 2024-06-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0008_parentcomments_mark_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcomments",
            name="mark_student_comment",
            field=models.BooleanField(default=False),
        ),
    ]
