# Generated by Django 5.0.4 on 2024-06-25 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0001_initial"),
        ("parents", "0009_studentcomments_mark_student_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentcomments",
            name="exam",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="corecode.examtype",
            ),
        ),
    ]
