# Generated by Django 5.0.4 on 2024-07-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0011_invoicecomments_installment_invoicecomments_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicecomments',
            name='term',
        ),
    ]
