# Generated by Django 5.0.4 on 2024-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academicanswer_date_commented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicanswer',
            name='mark_comment',
            field=models.BooleanField(default=False),
        ),
    ]
