# Generated by Django 5.0.4 on 2024-08-15 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursor', '0002_rename_created_at_bursoranswer_date_commented_and_more'),
        ('parents', '0012_remove_invoicecomments_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursoranswer',
            name='comment',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='parents.invoicecomments'),
            preserve_default=False,
        ),
    ]
